package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.freeDiskSpace
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        maven {
            goals = "clean package"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            clearConditions()
            mavenVersion = bundled_3_6()
        }
        insert(1) {
            maven {
                goals = "clean package"
            }
        }
    }

    features {
        add {
            freeDiskSpace {
                requiredSpace = "6gb"
                failBuild = false
            }
        }
        add {
            feature {
                type = ""
                param("free-space-work", "6gb")
            }
        }
    }
}
